project:
  type: website

execute:
  freeze: true
  
website:
  title: "IPBES_TCA_Fig_SPM.11_dynamic"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
output-dir: "doc"
