name: Render and Deploy Quarto Website

on:
  push:
    branches:
      - main  # Change this if your default branch has a different name

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.16"

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Render Quarto Project
        run: quarto render

      - name: Deploy to GitHub Pages (Root Directory)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site     # Change this if you set a different output-dir (e.g., "doc")
          target-folder: .  # Deploys files to the root of `gh-pages`
          clean: true       # Removes old files before deployment